version: '3.8'

services:
  antoni-ia-api:
    build: .
    container_name: antoni-ia-api
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.antoni-ia-api.rule=Host(`${SUBDOMINIO}`)"
      - "traefik.http.routers.antoni-ia-api.entrypoints=websecure"
      - "traefik.http.routers.antoni-ia-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.antoni-ia-api.loadbalancer.server.port=8000"

networks:
  traefik:
    external: true
